export const queryKeys = {
  agents: ["agents"] as const,
  agentReadiness: ["agent-readiness"] as const,
  agentRuns: ["agent-runs"] as const,
  agentVersions: ["agent-versions"] as const,
  chatAccessTokens: ["chat-access-tokens"] as const,
  credentials: ["credentials"] as const,
  discordBindings: ["discord-bindings"] as const,
  discordConnections: ["discord-connections"] as const,
  discordServers: ["discord-servers"] as const,
  jobs: ["jobs"] as const,
  knowledgeBases: ["knowledge-bases"] as const,
  modelAssignments: ["model-assignments"] as const,
  models: ["model-profiles"] as const,
  overview: ["operational-overview"] as const,
  providers: ["provider-endpoints"] as const,
  readiness: ["readiness"] as const,
  runs: ["documentation-runs"] as const,
  sources: ["sources"] as const,
  wiki: ["wiki"] as const,
};
