// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireEventSequenceLock = `-- name: AcquireEventSequenceLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('ref0.event-log.sequence', 0))
`

func (q *Queries) AcquireEventSequenceLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireEventSequenceLock)
	return err
}

const acquireJobAdmissionLock = `-- name: AcquireJobAdmissionLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('ref0.job-queue.admission', 0))
`

func (q *Queries) AcquireJobAdmissionLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireJobAdmissionLock)
	return err
}

const cancelJob = `-- name: CancelJob :execrows
UPDATE jobs
SET status = 'CANCELLED',
    lease_owner = NULL,
    lease_expires_at = NULL,
    not_before = NULL,
    result = NULL,
    sanitized_error = NULL,
    updated_at = $1,
    finished_at = $1
WHERE id = $2
`

type CancelJobParams struct {
	CurrentTime pgtype.Timestamptz `db:"current_time" json:"current_time"`
	JobID       pgtype.UUID        `db:"job_id" json:"job_id"`
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelJob, arg.CurrentTime, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const databaseClock = `-- name: DatabaseClock :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) DatabaseClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, databaseClock)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const expireAttempt = `-- name: ExpireAttempt :execrows
UPDATE job_attempts
SET heartbeat_at = $1,
    outcome = 'LEASE_EXPIRED',
    sanitized_error = $2::text,
    finished_at = $1
WHERE job_id = $3
  AND lease_generation = $4
`

type ExpireAttemptParams struct {
	CurrentTime     pgtype.Timestamptz `db:"current_time" json:"current_time"`
	SanitizedError  pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	JobID           pgtype.UUID        `db:"job_id" json:"job_id"`
	LeaseGeneration int64              `db:"lease_generation" json:"lease_generation"`
}

func (q *Queries) ExpireAttempt(ctx context.Context, arg ExpireAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireAttempt,
		arg.CurrentTime,
		arg.SanitizedError,
		arg.JobID,
		arg.LeaseGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveJobIDByOperationKey = `-- name: FindActiveJobIDByOperationKey :one
SELECT id
FROM jobs
WHERE operation_key = $1
  AND status IN ('PENDING', 'LEASED', 'RETRY_WAIT', 'CANCEL_REQUESTED')
`

func (q *Queries) FindActiveJobIDByOperationKey(ctx context.Context, operationKey string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findActiveJobIDByOperationKey, operationKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const finishAttempt = `-- name: FinishAttempt :execrows
UPDATE job_attempts
SET heartbeat_at = $1,
    outcome = $2,
    sanitized_error = $3::text,
    finished_at = $1
WHERE job_id = $4
  AND lease_generation = $5
`

type FinishAttemptParams struct {
	CurrentTime     pgtype.Timestamptz `db:"current_time" json:"current_time"`
	Outcome         pgtype.Text        `db:"outcome" json:"outcome"`
	SanitizedError  pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	JobID           pgtype.UUID        `db:"job_id" json:"job_id"`
	LeaseGeneration int64              `db:"lease_generation" json:"lease_generation"`
}

func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAttempt,
		arg.CurrentTime,
		arg.Outcome,
		arg.SanitizedError,
		arg.JobID,
		arg.LeaseGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishJob = `-- name: FinishJob :execrows
UPDATE jobs
SET status = $1::varchar(24),
    progress = CASE WHEN $1::varchar(24) = 'SUCCEEDED'::varchar(24) THEN 100 ELSE progress END,
    lease_owner = NULL,
    lease_expires_at = NULL,
    not_before = $2::timestamptz,
    result = $3::jsonb,
    sanitized_error = $4::text,
    updated_at = $5::timestamptz,
    finished_at = CASE WHEN $6::boolean THEN $5::timestamptz ELSE NULL::timestamptz END
WHERE id = $7
`

type FinishJobParams struct {
	Status         string             `db:"status" json:"status"`
	NotBefore      pgtype.Timestamptz `db:"not_before" json:"not_before"`
	Result         []byte             `db:"result" json:"result"`
	SanitizedError pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	CurrentTime    pgtype.Timestamptz `db:"current_time" json:"current_time"`
	Terminal       bool               `db:"terminal" json:"terminal"`
	JobID          pgtype.UUID        `db:"job_id" json:"job_id"`
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishJob,
		arg.Status,
		arg.NotBefore,
		arg.Result,
		arg.SanitizedError,
		arg.CurrentTime,
		arg.Terminal,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, job_type, target_type, target_id, payload, operation_key, concurrency_key, concurrency_limit, status, attempt_count, max_attempts, progress, lease_owner, lease_expires_at, lease_generation, not_before, result, sanitized_error, created_at, updated_at, started_at, finished_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, jobID pgtype.UUID) (*Job, error) {
	row := q.db.QueryRow(ctx, getJob, jobID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.TargetType,
		&i.TargetID,
		&i.Payload,
		&i.OperationKey,
		&i.ConcurrencyKey,
		&i.ConcurrencyLimit,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.Progress,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.LeaseGeneration,
		&i.NotBefore,
		&i.Result,
		&i.SanitizedError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const getJobCommand = `-- name: GetJobCommand :one
SELECT job_type, target_type, target_id, payload, operation_key, max_attempts, not_before,
       concurrency_key, concurrency_limit
FROM jobs
WHERE id = $1
`

type GetJobCommandRow struct {
	JobType          string             `db:"job_type" json:"job_type"`
	TargetType       string             `db:"target_type" json:"target_type"`
	TargetID         pgtype.UUID        `db:"target_id" json:"target_id"`
	Payload          []byte             `db:"payload" json:"payload"`
	OperationKey     string             `db:"operation_key" json:"operation_key"`
	MaxAttempts      int32              `db:"max_attempts" json:"max_attempts"`
	NotBefore        pgtype.Timestamptz `db:"not_before" json:"not_before"`
	ConcurrencyKey   string             `db:"concurrency_key" json:"concurrency_key"`
	ConcurrencyLimit int32              `db:"concurrency_limit" json:"concurrency_limit"`
}

func (q *Queries) GetJobCommand(ctx context.Context, jobID pgtype.UUID) (*GetJobCommandRow, error) {
	row := q.db.QueryRow(ctx, getJobCommand, jobID)
	var i GetJobCommandRow
	err := row.Scan(
		&i.JobType,
		&i.TargetType,
		&i.TargetID,
		&i.Payload,
		&i.OperationKey,
		&i.MaxAttempts,
		&i.NotBefore,
		&i.ConcurrencyKey,
		&i.ConcurrencyLimit,
	)
	return &i, err
}

const heartbeatAttempt = `-- name: HeartbeatAttempt :execrows
UPDATE job_attempts
SET heartbeat_at = $1
WHERE job_id = $2
  AND lease_generation = $3
`

type HeartbeatAttemptParams struct {
	CurrentTime     pgtype.Timestamptz `db:"current_time" json:"current_time"`
	JobID           pgtype.UUID        `db:"job_id" json:"job_id"`
	LeaseGeneration int64              `db:"lease_generation" json:"lease_generation"`
}

func (q *Queries) HeartbeatAttempt(ctx context.Context, arg HeartbeatAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatAttempt, arg.CurrentTime, arg.JobID, arg.LeaseGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const heartbeatJob = `-- name: HeartbeatJob :execrows
UPDATE jobs
SET lease_expires_at = $1::timestamptz + $2::bigint * interval '1 microsecond',
    updated_at = $1
WHERE id = $3
`

type HeartbeatJobParams struct {
	CurrentTime       pgtype.Timestamptz `db:"current_time" json:"current_time"`
	LeaseMicroseconds int64              `db:"lease_microseconds" json:"lease_microseconds"`
	JobID             pgtype.UUID        `db:"job_id" json:"job_id"`
}

func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatJob, arg.CurrentTime, arg.LeaseMicroseconds, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (
    job_type,
    target_type,
    target_id,
    payload,
    operation_key,
    concurrency_key,
    concurrency_limit,
    max_attempts,
    not_before,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4::jsonb,
    $5,
    $6,
    $7,
    $8,
    $9::timestamptz,
    $10,
    $10
)
ON CONFLICT (operation_key)
WHERE status IN ('PENDING', 'LEASED', 'RETRY_WAIT', 'CANCEL_REQUESTED')
DO NOTHING
RETURNING id
`

type InsertJobParams struct {
	JobType          string             `db:"job_type" json:"job_type"`
	TargetType       string             `db:"target_type" json:"target_type"`
	TargetID         pgtype.UUID        `db:"target_id" json:"target_id"`
	Payload          []byte             `db:"payload" json:"payload"`
	OperationKey     string             `db:"operation_key" json:"operation_key"`
	ConcurrencyKey   string             `db:"concurrency_key" json:"concurrency_key"`
	ConcurrencyLimit int32              `db:"concurrency_limit" json:"concurrency_limit"`
	MaxAttempts      int32              `db:"max_attempts" json:"max_attempts"`
	NotBefore        pgtype.Timestamptz `db:"not_before" json:"not_before"`
	CurrentTime      pgtype.Timestamptz `db:"current_time" json:"current_time"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.JobType,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
		arg.OperationKey,
		arg.ConcurrencyKey,
		arg.ConcurrencyLimit,
		arg.MaxAttempts,
		arg.NotBefore,
		arg.CurrentTime,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertJobAttempt = `-- name: InsertJobAttempt :exec
INSERT INTO job_attempts (
    job_id,
    attempt_number,
    lease_generation,
    worker_id,
    heartbeat_at,
    started_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $5
)
`

type InsertJobAttemptParams struct {
	JobID           pgtype.UUID        `db:"job_id" json:"job_id"`
	AttemptNumber   int32              `db:"attempt_number" json:"attempt_number"`
	LeaseGeneration int64              `db:"lease_generation" json:"lease_generation"`
	WorkerID        string             `db:"worker_id" json:"worker_id"`
	CurrentTime     pgtype.Timestamptz `db:"current_time" json:"current_time"`
}

func (q *Queries) InsertJobAttempt(ctx context.Context, arg InsertJobAttemptParams) error {
	_, err := q.db.Exec(ctx, insertJobAttempt,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseGeneration,
		arg.WorkerID,
		arg.CurrentTime,
	)
	return err
}

const insertJobEvent = `-- name: InsertJobEvent :exec
INSERT INTO job_events (
    job_id,
    attempt_number,
    event_kind,
    status,
    payload,
    created_at
)
SELECT
    id,
    $1::integer,
    $2,
    status,
    '{}'::jsonb,
    $3
FROM jobs
WHERE id = $4
`

type InsertJobEventParams struct {
	AttemptNumber pgtype.Int4        `db:"attempt_number" json:"attempt_number"`
	EventKind     string             `db:"event_kind" json:"event_kind"`
	CurrentTime   pgtype.Timestamptz `db:"current_time" json:"current_time"`
	JobID         pgtype.UUID        `db:"job_id" json:"job_id"`
}

func (q *Queries) InsertJobEvent(ctx context.Context, arg InsertJobEventParams) error {
	_, err := q.db.Exec(ctx, insertJobEvent,
		arg.AttemptNumber,
		arg.EventKind,
		arg.CurrentTime,
		arg.JobID,
	)
	return err
}

const insertJobResourceEvent = `-- name: InsertJobResourceEvent :exec
INSERT INTO event_log (
    event_type,
    resource_type,
    resource_id,
    snapshot,
    created_at
)
SELECT
    'job.' || lower($1::text),
    'job',
    id,
    jsonb_build_object(
        'id', id::text,
        'job_type', lower(job_type),
        'target_type', target_type,
        'target_id', target_id::text,
        'status', lower(status),
        'attempt_count', attempt_count,
        'max_attempts', max_attempts,
        'progress', progress,
        'lease_owner', lease_owner,
        'lease_expires_at', lease_expires_at,
        'lease_generation', lease_generation,
        'not_before', not_before,
        'result', result,
        'sanitized_error', sanitized_error,
        'created_at', created_at,
        'updated_at', updated_at,
        'started_at', started_at,
        'finished_at', finished_at
    ),
    $2
FROM jobs
WHERE id = $3
`

type InsertJobResourceEventParams struct {
	EventKind   string             `db:"event_kind" json:"event_kind"`
	CurrentTime pgtype.Timestamptz `db:"current_time" json:"current_time"`
	JobID       pgtype.UUID        `db:"job_id" json:"job_id"`
}

func (q *Queries) InsertJobResourceEvent(ctx context.Context, arg InsertJobResourceEventParams) error {
	_, err := q.db.Exec(ctx, insertJobResourceEvent, arg.EventKind, arg.CurrentTime, arg.JobID)
	return err
}

const leaseJob = `-- name: LeaseJob :execrows
UPDATE jobs
SET status = 'LEASED',
    attempt_count = $1,
    lease_owner = $2,
    lease_expires_at = $3::timestamptz + $4::bigint * interval '1 microsecond',
    lease_generation = $5,
    not_before = NULL,
    updated_at = $3,
    started_at = COALESCE(started_at, $3)
WHERE id = $6
`

type LeaseJobParams struct {
	AttemptNumber     int32              `db:"attempt_number" json:"attempt_number"`
	WorkerID          pgtype.Text        `db:"worker_id" json:"worker_id"`
	CurrentTime       pgtype.Timestamptz `db:"current_time" json:"current_time"`
	LeaseMicroseconds int64              `db:"lease_microseconds" json:"lease_microseconds"`
	LeaseGeneration   int64              `db:"lease_generation" json:"lease_generation"`
	JobID             pgtype.UUID        `db:"job_id" json:"job_id"`
}

func (q *Queries) LeaseJob(ctx context.Context, arg LeaseJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaseJob,
		arg.AttemptNumber,
		arg.WorkerID,
		arg.CurrentTime,
		arg.LeaseMicroseconds,
		arg.LeaseGeneration,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listJobAttempts = `-- name: ListJobAttempts :many
SELECT job_id, attempt_number, lease_generation, worker_id, heartbeat_at, outcome, sanitized_error, started_at, finished_at
FROM job_attempts
WHERE job_id = $1
ORDER BY attempt_number
`

func (q *Queries) ListJobAttempts(ctx context.Context, jobID pgtype.UUID) ([]*JobAttempt, error) {
	rows, err := q.db.Query(ctx, listJobAttempts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*JobAttempt{}
	for rows.Next() {
		var i JobAttempt
		if err := rows.Scan(
			&i.JobID,
			&i.AttemptNumber,
			&i.LeaseGeneration,
			&i.WorkerID,
			&i.HeartbeatAt,
			&i.Outcome,
			&i.SanitizedError,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT sequence, job_id, attempt_number, event_kind, status, payload, created_at
FROM job_events
WHERE job_id = $1
ORDER BY sequence
`

func (q *Queries) ListJobEvents(ctx context.Context, jobID pgtype.UUID) ([]*JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEvents, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.JobID,
			&i.AttemptNumber,
			&i.EventKind,
			&i.Status,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEligibleJob = `-- name: LockEligibleJob :one
SELECT candidate.id, candidate.status, candidate.attempt_count, candidate.max_attempts, candidate.lease_generation
FROM jobs candidate
WHERE ((
        status = 'PENDING'
        AND attempt_count < max_attempts
        AND (
            not_before IS NULL
            OR not_before <= COALESCE($1::timestamptz, clock_timestamp())
        )
    ) OR (
        status = 'RETRY_WAIT'
        AND attempt_count < max_attempts
        AND not_before <= COALESCE($1::timestamptz, clock_timestamp())
    ) OR (
        status IN ('LEASED', 'CANCEL_REQUESTED')
        AND lease_expires_at <= COALESCE($1::timestamptz, clock_timestamp())
    )) AND (
        candidate.concurrency_key = ''
        OR (
            SELECT count(*)
            FROM jobs active
            WHERE active.concurrency_key = candidate.concurrency_key
              AND active.status IN ('LEASED', 'CANCEL_REQUESTED')
              AND active.lease_expires_at > COALESCE($1::timestamptz, clock_timestamp())
        ) < candidate.concurrency_limit
    )
AND NOT EXISTS (
    SELECT 1 FROM model_profiles profile
    WHERE candidate.concurrency_key = 'model-profile:' || profile.id::text
      AND (
          (SELECT count(*) FROM provider_call_leases call
           WHERE call.endpoint_id=profile.endpoint_id AND call.expires_at > COALESCE($1::timestamptz, clock_timestamp()))
          + (SELECT count(*) FROM jobs active JOIN model_profiles model ON active.concurrency_key='model-profile:' || model.id::text
             WHERE model.endpoint_id=profile.endpoint_id AND active.status IN ('LEASED','CANCEL_REQUESTED')
               AND active.lease_expires_at > COALESCE($1::timestamptz, clock_timestamp()))
      ) >= (SELECT min(version.max_concurrent_tasks) FROM model_profiles model
            JOIN model_profile_versions version ON version.id=model.current_version_id
            WHERE model.endpoint_id=profile.endpoint_id)
)
ORDER BY candidate.created_at, candidate.id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type LockEligibleJobRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Status          string      `db:"status" json:"status"`
	AttemptCount    int32       `db:"attempt_count" json:"attempt_count"`
	MaxAttempts     int32       `db:"max_attempts" json:"max_attempts"`
	LeaseGeneration int64       `db:"lease_generation" json:"lease_generation"`
}

func (q *Queries) LockEligibleJob(ctx context.Context, now pgtype.Timestamptz) (*LockEligibleJobRow, error) {
	row := q.db.QueryRow(ctx, lockEligibleJob, now)
	var i LockEligibleJobRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseGeneration,
	)
	return &i, err
}

const lockJobForCancellation = `-- name: LockJobForCancellation :one
SELECT id, status, attempt_count, lease_expires_at, lease_generation
FROM jobs
WHERE id = $1
FOR UPDATE
`

type LockJobForCancellationRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Status          string             `db:"status" json:"status"`
	AttemptCount    int32              `db:"attempt_count" json:"attempt_count"`
	LeaseExpiresAt  pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	LeaseGeneration int64              `db:"lease_generation" json:"lease_generation"`
}

func (q *Queries) LockJobForCancellation(ctx context.Context, jobID pgtype.UUID) (*LockJobForCancellationRow, error) {
	row := q.db.QueryRow(ctx, lockJobForCancellation, jobID)
	var i LockJobForCancellationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AttemptCount,
		&i.LeaseExpiresAt,
		&i.LeaseGeneration,
	)
	return &i, err
}

const lockPermitJob = `-- name: LockPermitJob :one
SELECT id, status, attempt_count, max_attempts, lease_owner, lease_expires_at, lease_generation
FROM jobs
WHERE id = $1
FOR UPDATE
`

type LockPermitJobRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Status          string             `db:"status" json:"status"`
	AttemptCount    int32              `db:"attempt_count" json:"attempt_count"`
	MaxAttempts     int32              `db:"max_attempts" json:"max_attempts"`
	LeaseOwner      pgtype.Text        `db:"lease_owner" json:"lease_owner"`
	LeaseExpiresAt  pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	LeaseGeneration int64              `db:"lease_generation" json:"lease_generation"`
}

func (q *Queries) LockPermitJob(ctx context.Context, jobID pgtype.UUID) (*LockPermitJobRow, error) {
	row := q.db.QueryRow(ctx, lockPermitJob, jobID)
	var i LockPermitJobRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.LeaseGeneration,
	)
	return &i, err
}

const requestJobCancellation = `-- name: RequestJobCancellation :execrows
UPDATE jobs
SET status = 'CANCEL_REQUESTED',
    updated_at = $1
WHERE id = $2
`

type RequestJobCancellationParams struct {
	CurrentTime pgtype.Timestamptz `db:"current_time" json:"current_time"`
	JobID       pgtype.UUID        `db:"job_id" json:"job_id"`
}

func (q *Queries) RequestJobCancellation(ctx context.Context, arg RequestJobCancellationParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestJobCancellation, arg.CurrentTime, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
