// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	AgentKey         string             `db:"agent_key" json:"agent_key"`
	Lifecycle        string             `db:"lifecycle" json:"lifecycle"`
	CurrentVersionID pgtype.UUID        `db:"current_version_id" json:"current_version_id"`
	Version          int32              `db:"version" json:"version"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ActivatedAt      pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	ArchivedAt       pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
}

type AgentRun struct {
	ID                                   pgtype.UUID        `db:"id" json:"id"`
	AgentID                              pgtype.UUID        `db:"agent_id" json:"agent_id"`
	AgentVersionID                       pgtype.UUID        `db:"agent_version_id" json:"agent_version_id"`
	AgentResourceVersion                 int32              `db:"agent_resource_version" json:"agent_resource_version"`
	AgentVersionNumber                   int32              `db:"agent_version_number" json:"agent_version_number"`
	ModelProfileID                       pgtype.UUID        `db:"model_profile_id" json:"model_profile_id"`
	ModelProfileVersionID                pgtype.UUID        `db:"model_profile_version_id" json:"model_profile_version_id"`
	ModelProfileVersionNumber            int32              `db:"model_profile_version_number" json:"model_profile_version_number"`
	ProviderEndpointID                   pgtype.UUID        `db:"provider_endpoint_id" json:"provider_endpoint_id"`
	CapturedEndpointConfigurationVersion int32              `db:"captured_endpoint_configuration_version" json:"captured_endpoint_configuration_version"`
	CapturedCredentialID                 pgtype.UUID        `db:"captured_credential_id" json:"captured_credential_id"`
	CapturedCredentialVersion            pgtype.Int4        `db:"captured_credential_version" json:"captured_credential_version"`
	Origin                               string             `db:"origin" json:"origin"`
	Subject                              string             `db:"subject" json:"subject"`
	RequestDigest                        []byte             `db:"request_digest" json:"request_digest"`
	EffectiveAccessPolicy                string             `db:"effective_access_policy" json:"effective_access_policy"`
	Outcome                              string             `db:"outcome" json:"outcome"`
	ModelUsage                           []byte             `db:"model_usage" json:"model_usage"`
	LatencyMs                            int32              `db:"latency_ms" json:"latency_ms"`
	ToolCalls                            []byte             `db:"tool_calls" json:"tool_calls"`
	Citations                            []byte             `db:"citations" json:"citations"`
	SanitizedError                       pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	CreatedAt                            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CompletedAt                          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type AgentRunKnowledgeBasis struct {
	RunID                pgtype.UUID   `db:"run_id" json:"run_id"`
	Position             int32         `db:"position" json:"position"`
	KnowledgeBaseID      pgtype.UUID   `db:"knowledge_base_id" json:"knowledge_base_id"`
	KnowledgeBaseVersion int32         `db:"knowledge_base_version" json:"knowledge_base_version"`
	AccessPolicy         string        `db:"access_policy" json:"access_policy"`
	WikiVersionID        pgtype.UUID   `db:"wiki_version_id" json:"wiki_version_id"`
	DocumentationRunID   pgtype.UUID   `db:"documentation_run_id" json:"documentation_run_id"`
	SourceRevisionIds    []pgtype.UUID `db:"source_revision_ids" json:"source_revision_ids"`
	SourceScopeDigest    []byte        `db:"source_scope_digest" json:"source_scope_digest"`
}

type AgentRunScopeReservation struct {
	RunID           pgtype.UUID        `db:"run_id" json:"run_id"`
	Position        int32              `db:"position" json:"position"`
	KnowledgeBaseID pgtype.UUID        `db:"knowledge_base_id" json:"knowledge_base_id"`
	WikiVersionID   pgtype.UUID        `db:"wiki_version_id" json:"wiki_version_id"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AgentVersion struct {
	ID                     pgtype.UUID        `db:"id" json:"id"`
	AgentID                pgtype.UUID        `db:"agent_id" json:"agent_id"`
	VersionNumber          int32              `db:"version_number" json:"version_number"`
	DisplayName            string             `db:"display_name" json:"display_name"`
	Description            string             `db:"description" json:"description"`
	ResponseLanguage       string             `db:"response_language" json:"response_language"`
	IdentityInstructions   string             `db:"identity_instructions" json:"identity_instructions"`
	ModelProfileID         pgtype.UUID        `db:"model_profile_id" json:"model_profile_id"`
	ReasoningEffort        string             `db:"reasoning_effort" json:"reasoning_effort"`
	AnswerMode             string             `db:"answer_mode" json:"answer_mode"`
	BehavioralInstructions string             `db:"behavioral_instructions" json:"behavioral_instructions"`
	EvidenceAccess         string             `db:"evidence_access" json:"evidence_access"`
	RefusalMarkdown        string             `db:"refusal_markdown" json:"refusal_markdown"`
	MaxToolCalls           int32              `db:"max_tool_calls" json:"max_tool_calls"`
	MaxAnswerTokens        int32              `db:"max_answer_tokens" json:"max_answer_tokens"`
	CreatedByOperatorID    pgtype.UUID        `db:"created_by_operator_id" json:"created_by_operator_id"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AgentVersionKnowledgeBasis struct {
	AgentID         pgtype.UUID `db:"agent_id" json:"agent_id"`
	AgentVersionID  pgtype.UUID `db:"agent_version_id" json:"agent_version_id"`
	Position        int32       `db:"position" json:"position"`
	KnowledgeBaseID pgtype.UUID `db:"knowledge_base_id" json:"knowledge_base_id"`
}

type ArtifactDeletionIntent struct {
	Kind       string             `db:"kind" json:"kind"`
	ResourceID pgtype.UUID        `db:"resource_id" json:"resource_id"`
	OwnerID    pgtype.UUID        `db:"owner_id" json:"owner_id"`
	ScopeID    pgtype.UUID        `db:"scope_id" json:"scope_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuditEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ActorType  string             `db:"actor_type" json:"actor_type"`
	ActorID    pgtype.UUID        `db:"actor_id" json:"actor_id"`
	Action     string             `db:"action" json:"action"`
	TargetType string             `db:"target_type" json:"target_type"`
	TargetID   pgtype.UUID        `db:"target_id" json:"target_id"`
	RequestID  pgtype.UUID        `db:"request_id" json:"request_id"`
	Details    []byte             `db:"details" json:"details"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BootstrapToken struct {
	ID          int16              `db:"id" json:"id"`
	TokenDigest []byte             `db:"token_digest" json:"token_digest"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
}

type ChannelBinding struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ConnectionID      pgtype.UUID        `db:"connection_id" json:"connection_id"`
	ServerID          string             `db:"server_id" json:"server_id"`
	ListenChannelID   string             `db:"listen_channel_id" json:"listen_channel_id"`
	AgentID           pgtype.UUID        `db:"agent_id" json:"agent_id"`
	ReplyPolicy       string             `db:"reply_policy" json:"reply_policy"`
	ReplyChannelID    pgtype.Text        `db:"reply_channel_id" json:"reply_channel_id"`
	AllowedRoleIds    []byte             `db:"allowed_role_ids" json:"allowed_role_ids"`
	AllowedUserIds    []byte             `db:"allowed_user_ids" json:"allowed_user_ids"`
	RateRequests      int32              `db:"rate_requests" json:"rate_requests"`
	RateWindowSeconds int32              `db:"rate_window_seconds" json:"rate_window_seconds"`
	Enabled           bool               `db:"enabled" json:"enabled"`
	Health            string             `db:"health" json:"health"`
	SanitizedError    pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	ValidatedAt       pgtype.Timestamptz `db:"validated_at" json:"validated_at"`
	Version           int32              `db:"version" json:"version"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ChannelBindingTrigger struct {
	BindingID       pgtype.UUID        `db:"binding_id" json:"binding_id"`
	ConnectionID    pgtype.UUID        `db:"connection_id" json:"connection_id"`
	ServerID        string             `db:"server_id" json:"server_id"`
	ListenChannelID string             `db:"listen_channel_id" json:"listen_channel_id"`
	Enabled         bool               `db:"enabled" json:"enabled"`
	TriggerType     string             `db:"trigger_type" json:"trigger_type"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ChatAccessToken struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	TokenDigest         []byte             `db:"token_digest" json:"token_digest"`
	TokenPrefix         string             `db:"token_prefix" json:"token_prefix"`
	Label               string             `db:"label" json:"label"`
	CreatedByOperatorID pgtype.UUID        `db:"created_by_operator_id" json:"created_by_operator_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	LastUsedAt          pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

type ChatAccessTokenAgent struct {
	TokenID pgtype.UUID `db:"token_id" json:"token_id"`
	AgentID pgtype.UUID `db:"agent_id" json:"agent_id"`
}

type Claim struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	WikiVersionID pgtype.UUID `db:"wiki_version_id" json:"wiki_version_id"`
	WikiPageID    pgtype.UUID `db:"wiki_page_id" json:"wiki_page_id"`
	StableID      string      `db:"stable_id" json:"stable_id"`
	Statement     string      `db:"statement" json:"statement"`
	SearchVector  interface{} `db:"search_vector" json:"search_vector"`
}

type Credential struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Kind          string             `db:"kind" json:"kind"`
	Label         string             `db:"label" json:"label"`
	MaskedValue   string             `db:"masked_value" json:"masked_value"`
	KeyID         string             `db:"key_id" json:"key_id"`
	Nonce         []byte             `db:"nonce" json:"nonce"`
	Ciphertext    []byte             `db:"ciphertext" json:"ciphertext"`
	SecretVersion int32              `db:"secret_version" json:"secret_version"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RotatedAt     pgtype.Timestamptz `db:"rotated_at" json:"rotated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CredentialRotationAttempt struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	CredentialID     pgtype.UUID        `db:"credential_id" json:"credential_id"`
	OldSecretVersion int32              `db:"old_secret_version" json:"old_secret_version"`
	NewSecretVersion int32              `db:"new_secret_version" json:"new_secret_version"`
	NewKeyID         string             `db:"new_key_id" json:"new_key_id"`
	Status           string             `db:"status" json:"status"`
	SanitizedError   pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	ActorOperatorID  pgtype.UUID        `db:"actor_operator_id" json:"actor_operator_id"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt       pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type DiscordChannel struct {
	ConnectionID            pgtype.UUID        `db:"connection_id" json:"connection_id"`
	ServerID                string             `db:"server_id" json:"server_id"`
	ChannelID               string             `db:"channel_id" json:"channel_id"`
	ParentID                pgtype.Text        `db:"parent_id" json:"parent_id"`
	Name                    string             `db:"name" json:"name"`
	ChannelType             int32              `db:"channel_type" json:"channel_type"`
	Position                int32              `db:"position" json:"position"`
	EffectiveBotPermissions int64              `db:"effective_bot_permissions" json:"effective_bot_permissions"`
	EveryoneCanView         bool               `db:"everyone_can_view" json:"everyone_can_view"`
	RefreshedAt             pgtype.Timestamptz `db:"refreshed_at" json:"refreshed_at"`
	ViewerRoleIds           []byte             `db:"viewer_role_ids" json:"viewer_role_ids"`
	ViewerUserIds           []byte             `db:"viewer_user_ids" json:"viewer_user_ids"`
	AudienceOverwriteSha256 []byte             `db:"audience_overwrite_sha256" json:"audience_overwrite_sha256"`
}

type DiscordConnection struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	DisplayName       string             `db:"display_name" json:"display_name"`
	DisplayKey        string             `db:"display_key" json:"display_key"`
	CredentialID      pgtype.UUID        `db:"credential_id" json:"credential_id"`
	CredentialVersion int32              `db:"credential_version" json:"credential_version"`
	ApplicationID     pgtype.Text        `db:"application_id" json:"application_id"`
	BotUserID         pgtype.Text        `db:"bot_user_id" json:"bot_user_id"`
	BotUsername       pgtype.Text        `db:"bot_username" json:"bot_username"`
	AvatarHash        pgtype.Text        `db:"avatar_hash" json:"avatar_hash"`
	Lifecycle         string             `db:"lifecycle" json:"lifecycle"`
	State             string             `db:"state" json:"state"`
	GatewayLatencyMs  pgtype.Int4        `db:"gateway_latency_ms" json:"gateway_latency_ms"`
	LastHeartbeatAt   pgtype.Timestamptz `db:"last_heartbeat_at" json:"last_heartbeat_at"`
	LastEventAt       pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
	SanitizedError    pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	Version           int32              `db:"version" json:"version"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DiscordConversation struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	BindingID      pgtype.UUID        `db:"binding_id" json:"binding_id"`
	AgentID        pgtype.UUID        `db:"agent_id" json:"agent_id"`
	AgentVersionID pgtype.UUID        `db:"agent_version_id" json:"agent_version_id"`
	ExternalUserID string             `db:"external_user_id" json:"external_user_id"`
	DestinationID  string             `db:"destination_id" json:"destination_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastActivityAt pgtype.Timestamptz `db:"last_activity_at" json:"last_activity_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type DiscordConversationMessage struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	ConversationID  pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	Sequence        int32              `db:"sequence" json:"sequence"`
	Role            string             `db:"role" json:"role"`
	Markdown        string             `db:"markdown" json:"markdown"`
	EstimatedTokens int32              `db:"estimated_tokens" json:"estimated_tokens"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DiscordRole struct {
	ConnectionID pgtype.UUID        `db:"connection_id" json:"connection_id"`
	ServerID     string             `db:"server_id" json:"server_id"`
	RoleID       string             `db:"role_id" json:"role_id"`
	Name         string             `db:"name" json:"name"`
	Position     int32              `db:"position" json:"position"`
	RefreshedAt  pgtype.Timestamptz `db:"refreshed_at" json:"refreshed_at"`
}

type DiscordServer struct {
	ConnectionID pgtype.UUID        `db:"connection_id" json:"connection_id"`
	ServerID     string             `db:"server_id" json:"server_id"`
	Name         string             `db:"name" json:"name"`
	IconHash     pgtype.Text        `db:"icon_hash" json:"icon_hash"`
	Owner        bool               `db:"owner" json:"owner"`
	RefreshedAt  pgtype.Timestamptz `db:"refreshed_at" json:"refreshed_at"`
}

type DiscoveryRun struct {
	ID                           pgtype.UUID        `db:"id" json:"id"`
	EndpointID                   pgtype.UUID        `db:"endpoint_id" json:"endpoint_id"`
	JobID                        pgtype.UUID        `db:"job_id" json:"job_id"`
	CapturedConfigurationVersion int32              `db:"captured_configuration_version" json:"captured_configuration_version"`
	CapturedCredentialVersion    pgtype.Int4        `db:"captured_credential_version" json:"captured_credential_version"`
	TlsRequired                  bool               `db:"tls_required" json:"tls_required"`
	RequestedByOperatorID        pgtype.UUID        `db:"requested_by_operator_id" json:"requested_by_operator_id"`
	Status                       string             `db:"status" json:"status"`
	ModelIds                     []byte             `db:"model_ids" json:"model_ids"`
	RawResponse                  []byte             `db:"raw_response" json:"raw_response"`
	TlsVerified                  pgtype.Bool        `db:"tls_verified" json:"tls_verified"`
	AuthenticationSucceeded      pgtype.Bool        `db:"authentication_succeeded" json:"authentication_succeeded"`
	HttpStatus                   pgtype.Int4        `db:"http_status" json:"http_status"`
	ResponseSha256               []byte             `db:"response_sha256" json:"response_sha256"`
	ModelCount                   pgtype.Int4        `db:"model_count" json:"model_count"`
	SanitizedError               pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	CreatedAt                    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt                    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt                  pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type DocumentationPage struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	RunID                pgtype.UUID        `db:"run_id" json:"run_id"`
	JobID                pgtype.UUID        `db:"job_id" json:"job_id"`
	Position             int32              `db:"position" json:"position"`
	Slug                 string             `db:"slug" json:"slug"`
	Title                string             `db:"title" json:"title"`
	Purpose              string             `db:"purpose" json:"purpose"`
	RelatedPages         []byte             `db:"related_pages" json:"related_pages"`
	SourceSeedPaths      []byte             `db:"source_seed_paths" json:"source_seed_paths"`
	Status               string             `db:"status" json:"status"`
	SubmissionDigest     []byte             `db:"submission_digest" json:"submission_digest"`
	ContentSha256        []byte             `db:"content_sha256" json:"content_sha256"`
	ClaimsSha256         []byte             `db:"claims_sha256" json:"claims_sha256"`
	SanitizedError       pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	AttemptCount         int32              `db:"attempt_count" json:"attempt_count"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ModelCalls           int32              `db:"model_calls" json:"model_calls"`
	InputTokens          int32              `db:"input_tokens" json:"input_tokens"`
	OutputTokens         int32              `db:"output_tokens" json:"output_tokens"`
	TotalTokens          int32              `db:"total_tokens" json:"total_tokens"`
	TruncatedToolResults int32              `db:"truncated_tool_results" json:"truncated_tool_results"`
}

type DocumentationRun struct {
	ID                          pgtype.UUID        `db:"id" json:"id"`
	KnowledgeBaseID             pgtype.UUID        `db:"knowledge_base_id" json:"knowledge_base_id"`
	Status                      string             `db:"status" json:"status"`
	PrepareJobID                pgtype.UUID        `db:"prepare_job_id" json:"prepare_job_id"`
	KnowledgeBaseVersion        int32              `db:"knowledge_base_version" json:"knowledge_base_version"`
	Instructions                string             `db:"instructions" json:"instructions"`
	Language                    string             `db:"language" json:"language"`
	PriorWikiVersionID          pgtype.UUID        `db:"prior_wiki_version_id" json:"prior_wiki_version_id"`
	PlanDigest                  []byte             `db:"plan_digest" json:"plan_digest"`
	PublishedWikiVersionID      pgtype.UUID        `db:"published_wiki_version_id" json:"published_wiki_version_id"`
	SanitizedError              pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	CreatedAt                   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt                 pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	PlannerModelCalls           int32              `db:"planner_model_calls" json:"planner_model_calls"`
	PlannerInputTokens          int32              `db:"planner_input_tokens" json:"planner_input_tokens"`
	PlannerOutputTokens         int32              `db:"planner_output_tokens" json:"planner_output_tokens"`
	PlannerTotalTokens          int32              `db:"planner_total_tokens" json:"planner_total_tokens"`
	PlannerTruncatedToolResults int32              `db:"planner_truncated_tool_results" json:"planner_truncated_tool_results"`
}

type DocumentationRunModel struct {
	RunID                                pgtype.UUID `db:"run_id" json:"run_id"`
	Role                                 string      `db:"role" json:"role"`
	ModelProfileID                       pgtype.UUID `db:"model_profile_id" json:"model_profile_id"`
	ModelProfileVersionID                pgtype.UUID `db:"model_profile_version_id" json:"model_profile_version_id"`
	ProfileVersion                       int32       `db:"profile_version" json:"profile_version"`
	ProviderEndpointID                   pgtype.UUID `db:"provider_endpoint_id" json:"provider_endpoint_id"`
	CapturedEndpointConfigurationVersion int32       `db:"captured_endpoint_configuration_version" json:"captured_endpoint_configuration_version"`
	CapturedCredentialVersion            pgtype.Int4 `db:"captured_credential_version" json:"captured_credential_version"`
	ReasoningEffort                      string      `db:"reasoning_effort" json:"reasoning_effort"`
	MaxConcurrentTasks                   int32       `db:"max_concurrent_tasks" json:"max_concurrent_tasks"`
}

type DocumentationRunSource struct {
	ConfigurationVersion int32       `db:"configuration_version" json:"configuration_version"`
	RunID                pgtype.UUID `db:"run_id" json:"run_id"`
	SourceID             pgtype.UUID `db:"source_id" json:"source_id"`
	SourceRevisionID     pgtype.UUID `db:"source_revision_id" json:"source_revision_id"`
	Fingerprint          []byte      `db:"fingerprint" json:"fingerprint"`
	NativeVersion        string      `db:"native_version" json:"native_version"`
}

type EventLog struct {
	Sequence     int64              `db:"sequence" json:"sequence"`
	EventType    string             `db:"event_type" json:"event_type"`
	ResourceType string             `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID        `db:"resource_id" json:"resource_id"`
	Snapshot     []byte             `db:"snapshot" json:"snapshot"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EventStreamState struct {
	ID            int16              `db:"id" json:"id"`
	PrunedThrough int64              `db:"pruned_through" json:"pruned_through"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Evidence struct {
	ID                pgtype.UUID `db:"id" json:"id"`
	ClaimID           pgtype.UUID `db:"claim_id" json:"claim_id"`
	EvidenceID        string      `db:"evidence_id" json:"evidence_id"`
	SourceID          pgtype.UUID `db:"source_id" json:"source_id"`
	SourceRevisionID  pgtype.UUID `db:"source_revision_id" json:"source_revision_id"`
	SourceFingerprint []byte      `db:"source_fingerprint" json:"source_fingerprint"`
	NativeVersion     string      `db:"native_version" json:"native_version"`
	Path              string      `db:"path" json:"path"`
	StartLine         pgtype.Int4 `db:"start_line" json:"start_line"`
	EndLine           pgtype.Int4 `db:"end_line" json:"end_line"`
	Resource          string      `db:"resource" json:"resource"`
}

type IdempotencyRecord struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Scope         string             `db:"scope" json:"scope"`
	RequestKey    string             `db:"request_key" json:"request_key"`
	Operation     string             `db:"operation" json:"operation"`
	RequestDigest []byte             `db:"request_digest" json:"request_digest"`
	ResultType    string             `db:"result_type" json:"result_type"`
	ResultID      pgtype.UUID        `db:"result_id" json:"result_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type Job struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	JobType          string             `db:"job_type" json:"job_type"`
	TargetType       string             `db:"target_type" json:"target_type"`
	TargetID         pgtype.UUID        `db:"target_id" json:"target_id"`
	Payload          []byte             `db:"payload" json:"payload"`
	OperationKey     string             `db:"operation_key" json:"operation_key"`
	ConcurrencyKey   string             `db:"concurrency_key" json:"concurrency_key"`
	ConcurrencyLimit int32              `db:"concurrency_limit" json:"concurrency_limit"`
	Status           string             `db:"status" json:"status"`
	AttemptCount     int32              `db:"attempt_count" json:"attempt_count"`
	MaxAttempts      int32              `db:"max_attempts" json:"max_attempts"`
	Progress         int32              `db:"progress" json:"progress"`
	LeaseOwner       pgtype.Text        `db:"lease_owner" json:"lease_owner"`
	LeaseExpiresAt   pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	LeaseGeneration  int64              `db:"lease_generation" json:"lease_generation"`
	NotBefore        pgtype.Timestamptz `db:"not_before" json:"not_before"`
	Result           []byte             `db:"result" json:"result"`
	SanitizedError   pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt       pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type JobAttempt struct {
	JobID           pgtype.UUID        `db:"job_id" json:"job_id"`
	AttemptNumber   int32              `db:"attempt_number" json:"attempt_number"`
	LeaseGeneration int64              `db:"lease_generation" json:"lease_generation"`
	WorkerID        string             `db:"worker_id" json:"worker_id"`
	HeartbeatAt     pgtype.Timestamptz `db:"heartbeat_at" json:"heartbeat_at"`
	Outcome         pgtype.Text        `db:"outcome" json:"outcome"`
	SanitizedError  pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt      pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type JobEvent struct {
	Sequence      int64              `db:"sequence" json:"sequence"`
	JobID         pgtype.UUID        `db:"job_id" json:"job_id"`
	AttemptNumber pgtype.Int4        `db:"attempt_number" json:"attempt_number"`
	EventKind     string             `db:"event_kind" json:"event_kind"`
	Status        string             `db:"status" json:"status"`
	Payload       []byte             `db:"payload" json:"payload"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type KnowledgeBasis struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	NameKey           string             `db:"name_key" json:"name_key"`
	AccessPolicy      string             `db:"access_policy" json:"access_policy"`
	Lifecycle         string             `db:"lifecycle" json:"lifecycle"`
	Instructions      string             `db:"instructions" json:"instructions"`
	Language          string             `db:"language" json:"language"`
	PublishedWikiID   pgtype.UUID        `db:"published_wiki_id" json:"published_wiki_id"`
	ArchivedAt        pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	DeleteRequestedAt pgtype.Timestamptz `db:"delete_requested_at" json:"delete_requested_at"`
	PurgeAfter        pgtype.Timestamptz `db:"purge_after" json:"purge_after"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version           int32              `db:"version" json:"version"`
}

type ModelAssignment struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	KnowledgeBaseID pgtype.UUID        `db:"knowledge_base_id" json:"knowledge_base_id"`
	Role            string             `db:"role" json:"role"`
	ModelProfileID  pgtype.UUID        `db:"model_profile_id" json:"model_profile_id"`
	ReasoningEffort string             `db:"reasoning_effort" json:"reasoning_effort"`
	AnswerMode      string             `db:"answer_mode" json:"answer_mode"`
	Version         int32              `db:"version" json:"version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ModelProfile struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	EndpointID       pgtype.UUID        `db:"endpoint_id" json:"endpoint_id"`
	ModelID          string             `db:"model_id" json:"model_id"`
	Availability     string             `db:"availability" json:"availability"`
	CurrentVersionID pgtype.UUID        `db:"current_version_id" json:"current_version_id"`
	Version          int32              `db:"version" json:"version"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ModelProfileVersion struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	ProfileID                pgtype.UUID        `db:"profile_id" json:"profile_id"`
	VersionNumber            int32              `db:"version_number" json:"version_number"`
	ConfigurationVersion     int32              `db:"configuration_version" json:"configuration_version"`
	Transport                string             `db:"transport" json:"transport"`
	ContextWindowTokens      pgtype.Int4        `db:"context_window_tokens" json:"context_window_tokens"`
	MaxOutputTokens          pgtype.Int4        `db:"max_output_tokens" json:"max_output_tokens"`
	SupportsStreaming        pgtype.Bool        `db:"supports_streaming" json:"supports_streaming"`
	SupportsTools            pgtype.Bool        `db:"supports_tools" json:"supports_tools"`
	SupportsStructuredOutput pgtype.Bool        `db:"supports_structured_output" json:"supports_structured_output"`
	SupportsTemperature      pgtype.Bool        `db:"supports_temperature" json:"supports_temperature"`
	ReasoningTransport       string             `db:"reasoning_transport" json:"reasoning_transport"`
	ReasoningMapping         []byte             `db:"reasoning_mapping" json:"reasoning_mapping"`
	TimeoutSeconds           int32              `db:"timeout_seconds" json:"timeout_seconds"`
	MaxRetries               int32              `db:"max_retries" json:"max_retries"`
	MaxConcurrentTasks       int32              `db:"max_concurrent_tasks" json:"max_concurrent_tasks"`
	ExtraBody                []byte             `db:"extra_body" json:"extra_body"`
	MetadataOrigin           []byte             `db:"metadata_origin" json:"metadata_origin"`
	Source                   string             `db:"source" json:"source"`
	CreatedByOperatorID      pgtype.UUID        `db:"created_by_operator_id" json:"created_by_operator_id"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Operator struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	UsernameKey  string             `db:"username_key" json:"username_key"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	DisabledAt   pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version      int32              `db:"version" json:"version"`
}

type OperatorSession struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OperatorID  pgtype.UUID        `db:"operator_id" json:"operator_id"`
	TokenDigest []byte             `db:"token_digest" json:"token_digest"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type ProbeRun struct {
	ID                           pgtype.UUID        `db:"id" json:"id"`
	ModelProfileID               pgtype.UUID        `db:"model_profile_id" json:"model_profile_id"`
	JobID                        pgtype.UUID        `db:"job_id" json:"job_id"`
	CapturedConfigurationVersion int32              `db:"captured_configuration_version" json:"captured_configuration_version"`
	CapturedCredentialVersion    pgtype.Int4        `db:"captured_credential_version" json:"captured_credential_version"`
	CapturedProfileVersionID     pgtype.UUID        `db:"captured_profile_version_id" json:"captured_profile_version_id"`
	RequestedByOperatorID        pgtype.UUID        `db:"requested_by_operator_id" json:"requested_by_operator_id"`
	SelectedChecks               []byte             `db:"selected_checks" json:"selected_checks"`
	AcknowledgeCost              bool               `db:"acknowledge_cost" json:"acknowledge_cost"`
	Status                       string             `db:"status" json:"status"`
	Findings                     []byte             `db:"findings" json:"findings"`
	RawResponse                  []byte             `db:"raw_response" json:"raw_response"`
	SanitizedError               pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	ResultingVersionID           pgtype.UUID        `db:"resulting_version_id" json:"resulting_version_id"`
	CreatedAt                    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt                    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt                  pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type ProviderCallLease struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	EndpointID pgtype.UUID        `db:"endpoint_id" json:"endpoint_id"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type ProviderEndpoint struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	DisplayName          string             `db:"display_name" json:"display_name"`
	DisplayKey           string             `db:"display_key" json:"display_key"`
	BaseUrl              string             `db:"base_url" json:"base_url"`
	CredentialID         pgtype.UUID        `db:"credential_id" json:"credential_id"`
	Headers              []byte             `db:"headers" json:"headers"`
	ChatCompletionsPath  string             `db:"chat_completions_path" json:"chat_completions_path"`
	ResponsesPath        pgtype.Text        `db:"responses_path" json:"responses_path"`
	ModelsPath           string             `db:"models_path" json:"models_path"`
	AllowHttp            bool               `db:"allow_http" json:"allow_http"`
	AllowPrivateNetwork  bool               `db:"allow_private_network" json:"allow_private_network"`
	Lifecycle            string             `db:"lifecycle" json:"lifecycle"`
	Version              int32              `db:"version" json:"version"`
	ConfigurationVersion int32              `db:"configuration_version" json:"configuration_version"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ArchivedAt           pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	Health               string             `db:"health" json:"health"`
	HealthCheckedAt      pgtype.Timestamptz `db:"health_checked_at" json:"health_checked_at"`
}

type RateLimitBucket struct {
	BindingID       pgtype.UUID        `db:"binding_id" json:"binding_id"`
	ExternalUserID  string             `db:"external_user_id" json:"external_user_id"`
	WindowStartedAt pgtype.Timestamptz `db:"window_started_at" json:"window_started_at"`
	RequestCount    int32              `db:"request_count" json:"request_count"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type RepositorySource struct {
	SourceID            pgtype.UUID `db:"source_id" json:"source_id"`
	RemoteUrl           string      `db:"remote_url" json:"remote_url"`
	CredentialUsername  pgtype.Text `db:"credential_username" json:"credential_username"`
	CredentialID        pgtype.UUID `db:"credential_id" json:"credential_id"`
	RefKind             string      `db:"ref_kind" json:"ref_kind"`
	RefValue            string      `db:"ref_value" json:"ref_value"`
	IncludePatterns     []byte      `db:"include_patterns" json:"include_patterns"`
	ExcludePatterns     []byte      `db:"exclude_patterns" json:"exclude_patterns"`
	PollIntervalSeconds pgtype.Int4 `db:"poll_interval_seconds" json:"poll_interval_seconds"`
}

type Source struct {
	ID                            pgtype.UUID        `db:"id" json:"id"`
	KnowledgeBaseID               pgtype.UUID        `db:"knowledge_base_id" json:"knowledge_base_id"`
	Kind                          string             `db:"kind" json:"kind"`
	DisplayName                   string             `db:"display_name" json:"display_name"`
	DisplayKey                    string             `db:"display_key" json:"display_key"`
	Privacy                       string             `db:"privacy" json:"privacy"`
	Lifecycle                     string             `db:"lifecycle" json:"lifecycle"`
	Health                        string             `db:"health" json:"health"`
	SanitizedError                pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	CheckedAt                     pgtype.Timestamptz `db:"checked_at" json:"checked_at"`
	CurrentRevisionID             pgtype.UUID        `db:"current_revision_id" json:"current_revision_id"`
	Version                       int32              `db:"version" json:"version"`
	ConfigurationVersion          int32              `db:"configuration_version" json:"configuration_version"`
	ValidatedConfigurationVersion pgtype.Int4        `db:"validated_configuration_version" json:"validated_configuration_version"`
	CreatedAt                     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt                    pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	RemovedAt                     pgtype.Timestamptz `db:"removed_at" json:"removed_at"`
}

type SourceRevision struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SourceID         pgtype.UUID        `db:"source_id" json:"source_id"`
	ObservedRefKind  string             `db:"observed_ref_kind" json:"observed_ref_kind"`
	ObservedRef      string             `db:"observed_ref" json:"observed_ref"`
	NativeVersion    string             `db:"native_version" json:"native_version"`
	Fingerprint      []byte             `db:"fingerprint" json:"fingerprint"`
	ArtifactKey      string             `db:"artifact_key" json:"artifact_key"`
	FileCount        int32              `db:"file_count" json:"file_count"`
	ByteCount        int64              `db:"byte_count" json:"byte_count"`
	IgnoredPaths     []byte             `db:"ignored_paths" json:"ignored_paths"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ArtifactPurgedAt pgtype.Timestamptz `db:"artifact_purged_at" json:"artifact_purged_at"`
}

type SourceSync struct {
	ID                                pgtype.UUID        `db:"id" json:"id"`
	SourceID                          pgtype.UUID        `db:"source_id" json:"source_id"`
	JobID                             pgtype.UUID        `db:"job_id" json:"job_id"`
	SyncKind                          string             `db:"sync_kind" json:"sync_kind"`
	RequestedByOperatorID             pgtype.UUID        `db:"requested_by_operator_id" json:"requested_by_operator_id"`
	CapturedSourceVersion             int32              `db:"captured_source_version" json:"captured_source_version"`
	CapturedConfigurationVersion      int32              `db:"captured_configuration_version" json:"captured_configuration_version"`
	CapturedPrivacy                   string             `db:"captured_privacy" json:"captured_privacy"`
	CapturedRemoteUrl                 string             `db:"captured_remote_url" json:"captured_remote_url"`
	CapturedCredentialUsername        pgtype.Text        `db:"captured_credential_username" json:"captured_credential_username"`
	CapturedCredentialID              pgtype.UUID        `db:"captured_credential_id" json:"captured_credential_id"`
	CapturedCredentialVersion         pgtype.Int4        `db:"captured_credential_version" json:"captured_credential_version"`
	CapturedRefKind                   pgtype.Text        `db:"captured_ref_kind" json:"captured_ref_kind"`
	CapturedRefValue                  pgtype.Text        `db:"captured_ref_value" json:"captured_ref_value"`
	CapturedIncludePatterns           []byte             `db:"captured_include_patterns" json:"captured_include_patterns"`
	CapturedExcludePatterns           []byte             `db:"captured_exclude_patterns" json:"captured_exclude_patterns"`
	CandidateRevisionID               pgtype.UUID        `db:"candidate_revision_id" json:"candidate_revision_id"`
	Status                            string             `db:"status" json:"status"`
	ResultRevisionID                  pgtype.UUID        `db:"result_revision_id" json:"result_revision_id"`
	ResolvedNativeVersion             pgtype.Text        `db:"resolved_native_version" json:"resolved_native_version"`
	SanitizedError                    pgtype.Text        `db:"sanitized_error" json:"sanitized_error"`
	CreatedAt                         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt                         pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt                       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CapturedSourceKind                string             `db:"captured_source_kind" json:"captured_source_kind"`
	CapturedCredentialHeader          pgtype.Text        `db:"captured_credential_header" json:"captured_credential_header"`
	CapturedCredentialPrefix          pgtype.Text        `db:"captured_credential_prefix" json:"captured_credential_prefix"`
	CapturedMaxConcurrency            pgtype.Int4        `db:"captured_max_concurrency" json:"captured_max_concurrency"`
	CapturedRequestsPerSecond         pgtype.Int4        `db:"captured_requests_per_second" json:"captured_requests_per_second"`
	CapturedMaxPages                  pgtype.Int4        `db:"captured_max_pages" json:"captured_max_pages"`
	CapturedMaxPageBytes              pgtype.Int4        `db:"captured_max_page_bytes" json:"captured_max_page_bytes"`
	CapturedMaxTotalBytes             pgtype.Int8        `db:"captured_max_total_bytes" json:"captured_max_total_bytes"`
	CapturedMaxDepth                  pgtype.Int4        `db:"captured_max_depth" json:"captured_max_depth"`
	CapturedPreviousRevisionID        pgtype.UUID        `db:"captured_previous_revision_id" json:"captured_previous_revision_id"`
	CapturedAcquisitionMode           string             `db:"captured_acquisition_mode" json:"captured_acquisition_mode"`
	CapturedTinyfishCredentialID      pgtype.UUID        `db:"captured_tinyfish_credential_id" json:"captured_tinyfish_credential_id"`
	CapturedTinyfishCredentialVersion pgtype.Int4        `db:"captured_tinyfish_credential_version" json:"captured_tinyfish_credential_version"`
}

type WebsiteRevisionPage struct {
	SourceID             pgtype.UUID `db:"source_id" json:"source_id"`
	RevisionID           pgtype.UUID `db:"revision_id" json:"revision_id"`
	CanonicalUrl         string      `db:"canonical_url" json:"canonical_url"`
	ContentPath          string      `db:"content_path" json:"content_path"`
	ContentSha256        []byte      `db:"content_sha256" json:"content_sha256"`
	EvidenceUri          string      `db:"evidence_uri" json:"evidence_uri"`
	Freshness            string      `db:"freshness" json:"freshness"`
	Etag                 pgtype.Text `db:"etag" json:"etag"`
	LastModified         pgtype.Text `db:"last_modified" json:"last_modified"`
	ReusedFromRevisionID pgtype.UUID `db:"reused_from_revision_id" json:"reused_from_revision_id"`
}

type WebsiteSource struct {
	SourceID             pgtype.UUID `db:"source_id" json:"source_id"`
	RootUrl              string      `db:"root_url" json:"root_url"`
	CredentialHeader     pgtype.Text `db:"credential_header" json:"credential_header"`
	CredentialPrefix     pgtype.Text `db:"credential_prefix" json:"credential_prefix"`
	CredentialID         pgtype.UUID `db:"credential_id" json:"credential_id"`
	MaxConcurrency       int32       `db:"max_concurrency" json:"max_concurrency"`
	RequestsPerSecond    int32       `db:"requests_per_second" json:"requests_per_second"`
	MaxPages             int32       `db:"max_pages" json:"max_pages"`
	MaxPageBytes         int32       `db:"max_page_bytes" json:"max_page_bytes"`
	MaxTotalBytes        int64       `db:"max_total_bytes" json:"max_total_bytes"`
	MaxDepth             int32       `db:"max_depth" json:"max_depth"`
	PollIntervalSeconds  pgtype.Int4 `db:"poll_interval_seconds" json:"poll_interval_seconds"`
	AcquisitionMode      string      `db:"acquisition_mode" json:"acquisition_mode"`
	TinyfishCredentialID pgtype.UUID `db:"tinyfish_credential_id" json:"tinyfish_credential_id"`
}

type WikiPage struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	WikiVersionID pgtype.UUID `db:"wiki_version_id" json:"wiki_version_id"`
	Slug          string      `db:"slug" json:"slug"`
	Title         string      `db:"title" json:"title"`
	Description   string      `db:"description" json:"description"`
	PageType      string      `db:"page_type" json:"page_type"`
	ContentSha256 []byte      `db:"content_sha256" json:"content_sha256"`
	ClaimsSha256  []byte      `db:"claims_sha256" json:"claims_sha256"`
	Body          string      `db:"body" json:"body"`
	SearchVector  interface{} `db:"search_vector" json:"search_vector"`
}

type WikiVersion struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	KnowledgeBaseID    pgtype.UUID        `db:"knowledge_base_id" json:"knowledge_base_id"`
	DocumentationRunID pgtype.UUID        `db:"documentation_run_id" json:"documentation_run_id"`
	ArtifactKey        string             `db:"artifact_key" json:"artifact_key"`
	ManifestSha256     []byte             `db:"manifest_sha256" json:"manifest_sha256"`
	PageCount          int32              `db:"page_count" json:"page_count"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PublishedAt        pgtype.Timestamptz `db:"published_at" json:"published_at"`
}
